default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_db_dev
  username: postgres
  password: 12345
  host: localhost
  port: 5432

test:
  <<: *default
  database: recipe_app_db_test
  username: postgres
  password: 12345
  host: localhost
  port: 5432

production:
  <<: *default
  database: microverse_recipe_app_production
  username: microverse_recipe_app
  password: <%= ENV["MICROVERSE_RECIPE_APP_DATABASE_PASSWORD"] %>
